export const productsData = [
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$100",
    priceDiscount: "$80",
    discount: 30,
  },
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$50",
    priceDiscount: "$40",
    discount: 30,
  },
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$200",
    priceDiscount: "$150",
  },
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$300",
    priceDiscount: "$250",
  },
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$120",
    priceDiscount: "$90",
  },
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$80",
    priceDiscount: "$60",
  },
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$500",
    priceDiscount: "$450",
  },
  {
    image: "/tenis-2.png",
    type: "Tênis",
    name: "K-Swiss V8 - Masculino",
    price: "$150",
    priceDiscount: "$130",
  },
];
